Inline comment buttons
gamejolt/frontend-lib pull request #134
Opened 2019-07-30 09:56 UTC by nilllzz

2019-07-30 23:20 UTC, hworld commented on components/content/content-editor/content-editor.ts
> +	openedStartup = false;
add comment, maybe called it openedOnStartup?

2019-07-30 23:21 UTC, hworld commented on components/content/content-editor/content-editor.ts
> +	openedStartup = false;
actually, I don't know what to call it, because I really don't know what it does...

2019-07-30 23:22 UTC, hworld commented on components/form-vue/control/content/content.ts
> +	@Prop(String)
startupArg is too vague. I can't figure out what it does. Should we call these "Do on startup" or something? "execute-on-startup"? not sure

2019-08-03 11:17 UTC, YLivay requested changes
Same befuddlement as @hworld, we can talk about how better to describe this. its functional, just unclear.

2019-08-07 16:42 UTC, merged